version: '3.8'

services:
  # The main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.app # A separate Dockerfile for the app itself
    container_name: code_act_app
    command: python main.py --config /app/configs/default.json
    volumes:
      # Mount the entire project directory to allow for live code changes
      - .:/app
    networks:
      - code-act-net
    depends_on:
      - sandbox
    env_file:
      - .env # Pass environment variables from a .env file

  # The sandboxed code execution service
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile # Uses the Dockerfile we created for the sandbox
    container_name: code_act_sandbox
    ports:
      # Expose the sandbox port to the host machine for potential debugging
      - "8888:8888"
    networks:
      - code-act-net

networks:
  code-act-net:
    driver: bridge